name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
    - uses: actions/checkout@v4
    - name: make
      run: make -B build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
