name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: sdl2things
    - run: sudo apt install make git gcc libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libopenmpt-dev libminiupnpc-dev
    - name: cmake
      run: cmake -B build
    - name: make
      run: make -C build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
