name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - name: x86
            prefix: i686-w64-mingw32
          - name: x86_64
            prefix: x86_64-w64-mingw32

    runs-on: ubuntu-latest
    env:
      PREFIX: ${{ matrix.arch.prefix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          [ "${{ matrix.arch.name }}" = "x86" ] && PKGSUFFIX="i686" || PKGSUFFIX="x86-64"
          sudo apt install -y nasm build-essential libpng-dev zlib1g-dev libsdl2-dev libsdl2-mixer-dev libgme-dev libopenmpt-dev emscripten

      - name: Build SRB2
        run: |
          [ "${{ matrix.arch.name }}" = "x86" ] && IS64BIT="" || IS64BIT="64"
          emcmake -B build
          emmake make -C build -j 4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: srb2wow-windows-${{ matrix.arch.name }}-${{ github.sha }}
          path: |
            bin/
            src/comptime.h
